// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {zone} from '../models';

export function ExportDomain(arg1:number,arg2:number):Promise<void>;

export function ExportEmail(arg1:number,arg2:number):Promise<void>;

export function ExportMember(arg1:number,arg2:number):Promise<void>;

export function ExportSite(arg1:number,arg2:number):Promise<void>;

export function QueryAim(arg1:number,arg2:string,arg3:number,arg4:number):Promise<zone.QueryAimResult>;

export function QueryApk(arg1:number,arg2:string,arg3:number,arg4:number):Promise<zone.QueryApkResult>;

export function QueryCode(arg1:number,arg2:string,arg3:number,arg4:number):Promise<zone.QueryCodeResult>;

export function QueryDomain(arg1:number,arg2:string,arg3:number,arg4:number):Promise<zone.QueryDomainResult>;

export function QueryDwm(arg1:number,arg2:string,arg3:number,arg4:number):Promise<zone.QueryDwmResult>;

export function QueryEmail(arg1:number,arg2:string,arg3:number,arg4:number):Promise<zone.QueryEmailResult>;

export function QueryMember(arg1:number,arg2:string,arg3:number,arg4:number):Promise<zone.QueryMemberResult>;

export function QuerySite(arg1:number,arg2:string,arg3:number,arg4:number):Promise<zone.QuerySiteResult>;

export function SetAuth(arg1:string):Promise<void>;
