// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportDomain(arg1, arg2) {
  return window['go']['zone']['Bridge']['ExportDomain'](arg1, arg2);
}

export function ExportEmail(arg1, arg2) {
  return window['go']['zone']['Bridge']['ExportEmail'](arg1, arg2);
}

export function ExportMember(arg1, arg2) {
  return window['go']['zone']['Bridge']['ExportMember'](arg1, arg2);
}

export function ExportSite(arg1, arg2) {
  return window['go']['zone']['Bridge']['ExportSite'](arg1, arg2);
}

export function QueryAim(arg1, arg2, arg3, arg4) {
  return window['go']['zone']['Bridge']['QueryAim'](arg1, arg2, arg3, arg4);
}

export function QueryApk(arg1, arg2, arg3, arg4) {
  return window['go']['zone']['Bridge']['QueryApk'](arg1, arg2, arg3, arg4);
}

export function QueryCode(arg1, arg2, arg3, arg4) {
  return window['go']['zone']['Bridge']['QueryCode'](arg1, arg2, arg3, arg4);
}

export function QueryDomain(arg1, arg2, arg3, arg4) {
  return window['go']['zone']['Bridge']['QueryDomain'](arg1, arg2, arg3, arg4);
}

export function QueryDwm(arg1, arg2, arg3, arg4) {
  return window['go']['zone']['Bridge']['QueryDwm'](arg1, arg2, arg3, arg4);
}

export function QueryEmail(arg1, arg2, arg3, arg4) {
  return window['go']['zone']['Bridge']['QueryEmail'](arg1, arg2, arg3, arg4);
}

export function QueryMember(arg1, arg2, arg3, arg4) {
  return window['go']['zone']['Bridge']['QueryMember'](arg1, arg2, arg3, arg4);
}

export function QuerySite(arg1, arg2, arg3, arg4) {
  return window['go']['zone']['Bridge']['QuerySite'](arg1, arg2, arg3, arg4);
}

export function SetAuth(arg1) {
  return window['go']['zone']['Bridge']['SetAuth'](arg1);
}
