// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {quake} from '../models';

export function GetUserInfo():Promise<quake.User>;

export function RealtimeServiceDataExport(arg1:number,arg2:number,arg3:number):Promise<void>;

export function RealtimeServiceDataQuery(arg1:number,arg2:quake.RealtimeDataQueryOptions):Promise<quake.RealtimeServiceQueryResult>;

export function SetAuth(arg1:string):Promise<void>;
