// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUserInfo() {
  return window['go']['quake']['Bridge']['GetUserInfo']();
}

export function RealtimeServiceDataExport(arg1, arg2, arg3) {
  return window['go']['quake']['Bridge']['RealtimeServiceDataExport'](arg1, arg2, arg3);
}

export function RealtimeServiceDataQuery(arg1, arg2) {
  return window['go']['quake']['Bridge']['RealtimeServiceDataQuery'](arg1, arg2);
}

export function SetAuth(arg1) {
  return window['go']['quake']['Bridge']['SetAuth'](arg1);
}
