// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentDomain(arg1) {
  return window['go']['ip138']['Bridge']['GetCurrentDomain'](arg1);
}

export function GetCurrentIP(arg1) {
  return window['go']['ip138']['Bridge']['GetCurrentIP'](arg1);
}

export function GetHistoryIP(arg1) {
  return window['go']['ip138']['Bridge']['GetHistoryIP'](arg1);
}
