// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ip138} from '../models';

export function GetCurrentDomain(arg1:string):Promise<Array<ip138.DomainItem>>;

export function GetCurrentIP(arg1:string):Promise<{[key: string]: any}>;

export function GetHistoryIP(arg1:string):Promise<Array<ip138.IPItem>>;
