// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchInsert(arg1, arg2) {
  return window['go']['service']['FofaDBService']['BatchInsert'](arg1, arg2);
}

export function GetByPaginationAndTaskID(arg1, arg2, arg3) {
  return window['go']['service']['FofaDBService']['GetByPaginationAndTaskID'](arg1, arg2, arg3);
}

export function GetByTaskID(arg1) {
  return window['go']['service']['FofaDBService']['GetByTaskID'](arg1);
}
