// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fofa} from '../models';
import {models} from '../models';

export function BatchInsert(arg1:number,arg2:Array<fofa.Item>):Promise<void>;

export function GetByPaginationAndTaskID(arg1:number,arg2:number,arg3:number):Promise<Array<models.Fofa>>;

export function GetByTaskID(arg1:number):Promise<Array<models.Fofa>>;
