// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wechat} from '../models';

export function GetAllMiniProgram():Promise<Array<wechat.MiniProgram>>;
