// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {constraint} from '../models';

export function GetAllEvents():Promise<constraint.Event>;
