// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['exportlog']['Bridge']['Create'](arg1);
}

export function DeleteAll() {
  return window['go']['exportlog']['Bridge']['DeleteAll']();
}

export function FindByExportID(arg1) {
  return window['go']['exportlog']['Bridge']['FindByExportID'](arg1);
}

export function GetByOffset(arg1, arg2) {
  return window['go']['exportlog']['Bridge']['GetByOffset'](arg1, arg2);
}

export function MarkAllAsDeleted() {
  return window['go']['exportlog']['Bridge']['MarkAllAsDeleted']();
}

export function MarkAsDeleted(arg1) {
  return window['go']['exportlog']['Bridge']['MarkAsDeleted'](arg1);
}

export function Update(arg1) {
  return window['go']['exportlog']['Bridge']['Update'](arg1);
}
