// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {exportlog} from '../models';

export function Create(arg1:string):Promise<number>;

export function DeleteAll():Promise<void>;

export function FindByExportID(arg1:number):Promise<models.ExportLog>;

export function GetByOffset(arg1:number,arg2:number):Promise<Record<string, any>>;

export function MarkAllAsDeleted():Promise<void>;

export function MarkAsDeleted(arg1:number):Promise<void>;

export function Update(arg1:exportlog.Item):Promise<void>;
