// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clear() {
  return window['go']['repository']['DownloadLogService']['Clear']();
}

export function GetByOffset(arg1, arg2) {
  return window['go']['repository']['DownloadLogService']['GetByOffset'](arg1, arg2);
}

export function GetByPagination(arg1, arg2) {
  return window['go']['repository']['DownloadLogService']['GetByPagination'](arg1, arg2);
}

export function GetRunningOrErrorOccurredTask() {
  return window['go']['repository']['DownloadLogService']['GetRunningOrErrorOccurredTask']();
}

export function Insert(arg1, arg2) {
  return window['go']['repository']['DownloadLogService']['Insert'](arg1, arg2);
}

export function MarkAsDeleted(arg1) {
  return window['go']['repository']['DownloadLogService']['MarkAsDeleted'](arg1);
}

export function UpdateStatus(arg1, arg2, arg3) {
  return window['go']['repository']['DownloadLogService']['UpdateStatus'](arg1, arg2, arg3);
}
