// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDetail(arg1:Array<string>):Promise<number>;

export function Stop(arg1:number):Promise<void>;
