// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDetail(arg1) {
  return window['go']['domain2ip']['Bridge']['GetDetail'](arg1);
}

export function Stop(arg1) {
  return window['go']['domain2ip']['Bridge']['Stop'](arg1);
}
