// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuth(arg1) {
  return window['go']['config']['Config']['CheckAuth'](arg1);
}

export function Get0zoneAuth() {
  return window['go']['config']['Config']['Get0zoneAuth']();
}

export function GetAll() {
  return window['go']['config']['Config']['GetAll']();
}

export function GetConfigAbsFilePath() {
  return window['go']['config']['Config']['GetConfigAbsFilePath']();
}

export function GetConfigBaseDir() {
  return window['go']['config']['Config']['GetConfigBaseDir']();
}

export function GetConfigFromFile() {
  return window['go']['config']['Config']['GetConfigFromFile']();
}

export function GetDBFile() {
  return window['go']['config']['Config']['GetDBFile']();
}

export function GetDataBaseDir() {
  return window['go']['config']['Config']['GetDataBaseDir']();
}

export function GetDefaultInterval() {
  return window['go']['config']['Config']['GetDefaultInterval']();
}

export function GetDefaultTimeout() {
  return window['go']['config']['Config']['GetDefaultTimeout']();
}

export function GetFofaAuth() {
  return window['go']['config']['Config']['GetFofaAuth']();
}

export function GetHttpx() {
  return window['go']['config']['Config']['GetHttpx']();
}

export function GetHunterAuth() {
  return window['go']['config']['Config']['GetHunterAuth']();
}

export function GetProxy() {
  return window['go']['config']['Config']['GetProxy']();
}

export function GetQuakeAuth() {
  return window['go']['config']['Config']['GetQuakeAuth']();
}

export function GetWxDataCacheDir() {
  return window['go']['config']['Config']['GetWxDataCacheDir']();
}

export function Init() {
  return window['go']['config']['Config']['Init']();
}

export function Save0zoneAuth(arg1) {
  return window['go']['config']['Config']['Save0zoneAuth'](arg1);
}

export function SaveConf(arg1) {
  return window['go']['config']['Config']['SaveConf'](arg1);
}

export function SaveFofaAuth(arg1, arg2) {
  return window['go']['config']['Config']['SaveFofaAuth'](arg1, arg2);
}

export function SaveHttpx(arg1) {
  return window['go']['config']['Config']['SaveHttpx'](arg1);
}

export function SaveHunterAuth(arg1) {
  return window['go']['config']['Config']['SaveHunterAuth'](arg1);
}

export function SaveProxy(arg1) {
  return window['go']['config']['Config']['SaveProxy'](arg1);
}

export function SaveQuakeAuth(arg1) {
  return window['go']['config']['Config']['SaveQuakeAuth'](arg1);
}

export function SaveWxDataCacheDir(arg1) {
  return window['go']['config']['Config']['SaveWxDataCacheDir'](arg1);
}
