// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function Get0zone():Promise<config.Zone>;

export function GetConfigBaseDir():Promise<string>;

export function GetConfigFilePath():Promise<string>;

export function GetDBFile():Promise<string>;

export function GetDNS():Promise<config.DNS>;

export function GetDataDir():Promise<string>;

export function GetFofa():Promise<config.Fofa>;

export function GetHttpx():Promise<config.Httpx>;

export function GetHunter():Promise<config.Hunter>;

export function GetProxy():Promise<config.Proxy>;

export function GetQuake():Promise<config.Quake>;

export function GetWechat():Promise<config.Wechat>;

export function GetWechatDataPath():Promise<string>;

export function Save0zone(arg1:config.Zone):Promise<void>;

export function SaveDNS(arg1:config.DNS):Promise<void>;

export function SaveFofa(arg1:config.Fofa):Promise<void>;

export function SaveHttpx(arg1:config.Httpx):Promise<void>;

export function SaveHunter(arg1:config.Hunter):Promise<void>;

export function SaveProxy(arg1:config.Proxy):Promise<void>;

export function SaveQuake(arg1:config.Quake):Promise<void>;

export function SaveWechat(arg1:config.Wechat):Promise<void>;

export function SaveWechatDataPath(arg1:string):Promise<void>;
