// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get0zone() {
  return window['go']['config']['Config']['Get0zone']();
}

export function GetConfigBaseDir() {
  return window['go']['config']['Config']['GetConfigBaseDir']();
}

export function GetConfigFilePath() {
  return window['go']['config']['Config']['GetConfigFilePath']();
}

export function GetDBFile() {
  return window['go']['config']['Config']['GetDBFile']();
}

export function GetDNS() {
  return window['go']['config']['Config']['GetDNS']();
}

export function GetDataDir() {
  return window['go']['config']['Config']['GetDataDir']();
}

export function GetFofa() {
  return window['go']['config']['Config']['GetFofa']();
}

export function GetHttpx() {
  return window['go']['config']['Config']['GetHttpx']();
}

export function GetHunter() {
  return window['go']['config']['Config']['GetHunter']();
}

export function GetProxy() {
  return window['go']['config']['Config']['GetProxy']();
}

export function GetQuake() {
  return window['go']['config']['Config']['GetQuake']();
}

export function GetWechat() {
  return window['go']['config']['Config']['GetWechat']();
}

export function GetWechatDataPath() {
  return window['go']['config']['Config']['GetWechatDataPath']();
}

export function Save0zone(arg1) {
  return window['go']['config']['Config']['Save0zone'](arg1);
}

export function SaveDNS(arg1) {
  return window['go']['config']['Config']['SaveDNS'](arg1);
}

export function SaveFofa(arg1) {
  return window['go']['config']['Config']['SaveFofa'](arg1);
}

export function SaveHttpx(arg1) {
  return window['go']['config']['Config']['SaveHttpx'](arg1);
}

export function SaveHunter(arg1) {
  return window['go']['config']['Config']['SaveHunter'](arg1);
}

export function SaveProxy(arg1) {
  return window['go']['config']['Config']['SaveProxy'](arg1);
}

export function SaveQuake(arg1) {
  return window['go']['config']['Config']['SaveQuake'](arg1);
}

export function SaveWechat(arg1) {
  return window['go']['config']['Config']['SaveWechat'](arg1);
}

export function SaveWechatDataPath(arg1) {
  return window['go']['config']['Config']['SaveWechatDataPath'](arg1);
}
