// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlatform():Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFile(arg1:string,arg2:string):Promise<void>;

export function OpenFileDialog():Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function ReadFileAsBase64(arg1:string):Promise<string>;

export function ShowItemInFolder(arg1:string,arg2:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
