// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['runtime']['Runtime']['CheckUpdate']();
}

export function GetPlatform() {
  return window['go']['runtime']['Runtime']['GetPlatform']();
}

export function OpenDirectoryDialog() {
  return window['go']['runtime']['Runtime']['OpenDirectoryDialog']();
}

export function OpenFile(arg1, arg2) {
  return window['go']['runtime']['Runtime']['OpenFile'](arg1, arg2);
}

export function OpenFileDialog() {
  return window['go']['runtime']['Runtime']['OpenFileDialog']();
}

export function OpenFolder(arg1) {
  return window['go']['runtime']['Runtime']['OpenFolder'](arg1);
}

export function ReadFileAsBase64(arg1) {
  return window['go']['runtime']['Runtime']['ReadFileAsBase64'](arg1);
}

export function ShowItemInFolder(arg1, arg2) {
  return window['go']['runtime']['Runtime']['ShowItemInFolder'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['runtime']['Runtime']['WriteFile'](arg1, arg2);
}
