// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wechat} from '../models';

export function Decompile(arg1:string,arg2:string):Promise<void>;

export function GetAppletSubDir():Promise<wechat.WxapkgInfo>;

export function SetAppletPath(arg1:string):Promise<void>;
