// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wechat} from '../models';

export function ClearApplet():Promise<void>;

export function Decompile(arg1:Array<wechat.MiniProgram>):Promise<void>;

export function GetAllMiniProgram():Promise<Array<wechat.MiniProgram>>;

export function SetAppletPath(arg1:string):Promise<void>;

export function Test1():Promise<Array<wechat.MiniProgram>>;

export function Test2():Promise<Array<wechat.TestB>>;
