// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearApplet() {
  return window['go']['wechat']['Bridge']['ClearApplet']();
}

export function ClearDecompiled() {
  return window['go']['wechat']['Bridge']['ClearDecompiled']();
}

export function Decompile(arg1) {
  return window['go']['wechat']['Bridge']['Decompile'](arg1);
}

export function GetAllMiniProgram() {
  return window['go']['wechat']['Bridge']['GetAllMiniProgram']();
}

export function SetAppletPath(arg1) {
  return window['go']['wechat']['Bridge']['SetAppletPath'](arg1);
}
