// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decompile(arg1, arg2) {
  return window['go']['wechat']['Bridge']['Decompile'](arg1, arg2);
}

export function GetAppletSubDir() {
  return window['go']['wechat']['Bridge']['GetAppletSubDir']();
}

export function SetAppletPath(arg1) {
  return window['go']['wechat']['Bridge']['SetAppletPath'](arg1);
}
