// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoDecompile(arg1) {
  return window['go']['wechat']['Bridge']['AutoDecompile'](arg1);
}

export function ClearApplet() {
  return window['go']['wechat']['Bridge']['ClearApplet']();
}

export function ClearDecompiled() {
  return window['go']['wechat']['Bridge']['ClearDecompiled']();
}

export function Decompile(arg1) {
  return window['go']['wechat']['Bridge']['Decompile'](arg1);
}

export function GetAllMiniApp() {
  return window['go']['wechat']['Bridge']['GetAllMiniApp']();
}

export function GetInfo(arg1) {
  return window['go']['wechat']['Bridge']['GetInfo'](arg1);
}

export function GetMatchedString(arg1, arg2) {
  return window['go']['wechat']['Bridge']['GetMatchedString'](arg1, arg2);
}

export function SaveWechatRules(arg1) {
  return window['go']['wechat']['Bridge']['SaveWechatRules'](arg1);
}

export function SetAppletPath(arg1) {
  return window['go']['wechat']['Bridge']['SetAppletPath'](arg1);
}

export function SetRegex(arg1) {
  return window['go']['wechat']['Bridge']['SetRegex'](arg1);
}

export function UseProxyManager(arg1) {
  return window['go']['wechat']['Bridge']['UseProxyManager'](arg1);
}
