// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {icp} from '../models';

export function CheckImage(arg1:string):Promise<any>;

export function Export(arg1:number):Promise<void>;

export function GetImage():Promise<icp.Image>;

export function GetItem():Promise<icp.Item>;

export function IsSignExpired():Promise<boolean>;

export function Query(arg1:string,arg2:number,arg3:number,arg4:string):Promise<{[key: string]: any}>;
