// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckImage(arg1) {
  return window['go']['icp']['Bridge']['CheckImage'](arg1);
}

export function Export(arg1) {
  return window['go']['icp']['Bridge']['Export'](arg1);
}

export function GetImage() {
  return window['go']['icp']['Bridge']['GetImage']();
}

export function GetItem() {
  return window['go']['icp']['Bridge']['GetItem']();
}

export function IsSignExpired() {
  return window['go']['icp']['Bridge']['IsSignExpired']();
}

export function Query(arg1, arg2, arg3, arg4) {
  return window['go']['icp']['Bridge']['Query'](arg1, arg2, arg3, arg4);
}
