// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['icp']['Bridge']['CreateTask'](arg1, arg2, arg3);
}

export function DeleteTask(arg1) {
  return window['go']['icp']['Bridge']['DeleteTask'](arg1);
}

export function Export(arg1) {
  return window['go']['icp']['Bridge']['Export'](arg1);
}

export function ExportCache(arg1, arg2) {
  return window['go']['icp']['Bridge']['ExportCache'](arg1, arg2);
}

export function ExportTaskData(arg1, arg2) {
  return window['go']['icp']['Bridge']['ExportTaskData'](arg1, arg2);
}

export function GetItem() {
  return window['go']['icp']['Bridge']['GetItem']();
}

export function GetModel() {
  return window['go']['icp']['Bridge']['GetModel']();
}

export function GetRunningTaskNum() {
  return window['go']['icp']['Bridge']['GetRunningTaskNum']();
}

export function GetTaskByID(arg1) {
  return window['go']['icp']['Bridge']['GetTaskByID'](arg1);
}

export function GetTaskData(arg1, arg2, arg3, arg4) {
  return window['go']['icp']['Bridge']['GetTaskData'](arg1, arg2, arg3, arg4);
}

export function GetTaskList(arg1, arg2, arg3) {
  return window['go']['icp']['Bridge']['GetTaskList'](arg1, arg2, arg3);
}

export function PauseAllTask() {
  return window['go']['icp']['Bridge']['PauseAllTask']();
}

export function PauseTask(arg1) {
  return window['go']['icp']['Bridge']['PauseTask'](arg1);
}

export function Query(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['icp']['Bridge']['Query'](arg1, arg2, arg3, arg4, arg5);
}

export function ResumeTask(arg1) {
  return window['go']['icp']['Bridge']['ResumeTask'](arg1);
}

export function RunTask(arg1) {
  return window['go']['icp']['Bridge']['RunTask'](arg1);
}

export function SetProxy(arg1) {
  return window['go']['icp']['Bridge']['SetProxy'](arg1);
}

export function SetProxyTimeout(arg1) {
  return window['go']['icp']['Bridge']['SetProxyTimeout'](arg1);
}

export function UpdateTaskName(arg1, arg2) {
  return window['go']['icp']['Bridge']['UpdateTaskName'](arg1, arg2);
}
