// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {icp} from '../models';

export function BatchQuery(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function Export(arg1:number):Promise<void>;

export function GetItem():Promise<icp.Item>;

export function Query(arg1:number,arg2:string,arg3:number,arg4:number,arg5:string):Promise<{[key: string]: any}>;
