// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Export(arg1) {
  return window['go']['icp']['Bridge']['Export'](arg1);
}

export function ExportCache(arg1, arg2) {
  return window['go']['icp']['Bridge']['ExportCache'](arg1, arg2);
}

export function GetItem() {
  return window['go']['icp']['Bridge']['GetItem']();
}

export function GetModel() {
  return window['go']['icp']['Bridge']['GetModel']();
}

export function GetRunningTaskNum() {
  return window['go']['icp']['Bridge']['GetRunningTaskNum']();
}

export function Query(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['icp']['Bridge']['Query'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveICPConfig(arg1) {
  return window['go']['icp']['Bridge']['SaveICPConfig'](arg1);
}

export function SetProxy(arg1) {
  return window['go']['icp']['Bridge']['SetProxy'](arg1);
}

export function SetProxyTimeout(arg1) {
  return window['go']['icp']['Bridge']['SetProxyTimeout'](arg1);
}

export function TaskCreate(arg1, arg2, arg3) {
  return window['go']['icp']['Bridge']['TaskCreate'](arg1, arg2, arg3);
}

export function TaskDelete(arg1) {
  return window['go']['icp']['Bridge']['TaskDelete'](arg1);
}

export function TaskExportData(arg1, arg2) {
  return window['go']['icp']['Bridge']['TaskExportData'](arg1, arg2);
}

export function TaskGetByID(arg1) {
  return window['go']['icp']['Bridge']['TaskGetByID'](arg1);
}

export function TaskGetData(arg1, arg2, arg3, arg4) {
  return window['go']['icp']['Bridge']['TaskGetData'](arg1, arg2, arg3, arg4);
}

export function TaskGetList(arg1, arg2, arg3) {
  return window['go']['icp']['Bridge']['TaskGetList'](arg1, arg2, arg3);
}

export function TaskPause(arg1) {
  return window['go']['icp']['Bridge']['TaskPause'](arg1);
}

export function TaskPauseAll() {
  return window['go']['icp']['Bridge']['TaskPauseAll']();
}

export function TaskResume(arg1) {
  return window['go']['icp']['Bridge']['TaskResume'](arg1);
}

export function TaskRun(arg1) {
  return window['go']['icp']['Bridge']['TaskRun'](arg1);
}

export function TaskUpdateName(arg1, arg2) {
  return window['go']['icp']['Bridge']['TaskUpdateName'](arg1, arg2);
}
