// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {aiqicha} from '../models';

export function ExportAllCopyright(arg1:string):Promise<number>;

export function GetBranchList(arg1:string,arg2:number):Promise<number>;

export function GetCopyrightList(arg1:string,arg2:number):Promise<number>;

export function GetInvestRecord(arg1:string):Promise<Array<aiqicha.InvestRecord>>;

export function GetShareholder(arg1:string):Promise<Array<aiqicha.Shareholder>>;

export function GetStockChart(arg1:string):Promise<aiqicha.Penetration>;

export function SetAuth(arg1:string):Promise<void>;

export function Suggest(arg1:string):Promise<Array<aiqicha.SuggestItem>>;
