// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCopyrightList(arg1, arg2) {
  return window['go']['aiqicha']['Bridge']['GetCopyrightList'](arg1, arg2);
}

export function GetInvestRecord(arg1) {
  return window['go']['aiqicha']['Bridge']['GetInvestRecord'](arg1);
}

export function GetShareholder(arg1) {
  return window['go']['aiqicha']['Bridge']['GetShareholder'](arg1);
}

export function GetStockChart(arg1) {
  return window['go']['aiqicha']['Bridge']['GetStockChart'](arg1);
}

export function SetAuth(arg1) {
  return window['go']['aiqicha']['Bridge']['SetAuth'](arg1);
}

export function Suggest(arg1) {
  return window['go']['aiqicha']['Bridge']['Suggest'](arg1);
}
