// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Fetch(arg1:string):Promise<Array<number>>;

export function GetContext():Promise<context.Context>;

export function SetContext(arg1:context.Context):Promise<void>;
