// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function SetContext(arg1) {
  return window['go']['app']['App']['SetContext'](arg1);
}
