// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Fetch(arg1) {
  return window['go']['app']['App']['Fetch'](arg1);
}

export function GetAllConstants() {
  return window['go']['app']['App']['GetAllConstants']();
}

export function GetContext() {
  return window['go']['app']['App']['GetContext']();
}

export function SaveProxy(arg1) {
  return window['go']['app']['App']['SaveProxy'](arg1);
}

export function SaveQueryOnEnter(arg1) {
  return window['go']['app']['App']['SaveQueryOnEnter'](arg1);
}

export function SaveWechat(arg1) {
  return window['go']['app']['App']['SaveWechat'](arg1);
}

export function SetContext(arg1) {
  return window['go']['app']['App']['SetContext'](arg1);
}

export function UseProxyManager(arg1) {
  return window['go']['app']['App']['UseProxyManager'](arg1);
}
