// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {context} from '../models';
import {config} from '../models';
import {proxy} from '../models';

export function Fetch(arg1:string):Promise<Array<number>>;

export function GetAllConstants():Promise<app.Constant>;

export function GetContext():Promise<context.Context>;

export function SaveProxy(arg1:config.Proxy):Promise<void>;

export function SaveQueryOnEnter(arg1:config.QueryOnEnter):Promise<void>;

export function SaveWechat(arg1:config.Wechat):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UseProxyManager(arg1:proxy.Manager):Promise<void>;
