// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Run(arg1, arg2, arg3) {
  return window['go']['httpx']['Bridge']['Run'](arg1, arg2, arg3);
}

export function SetConfig(arg1, arg2) {
  return window['go']['httpx']['Bridge']['SetConfig'](arg1, arg2);
}

export function Stop(arg1) {
  return window['go']['httpx']['Bridge']['Stop'](arg1);
}
