// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tianyancha} from '../models';

export function GetHolder(arg1:string):Promise<Array<tianyancha.PenetrationItem>>;

export function GetInvestee(arg1:string):Promise<Array<tianyancha.PenetrationItem>>;

export function SearchCompanyV4():Promise<Array<tianyancha.SearchCompanyV4Item>>;

export function SetAuth(arg1:string):Promise<void>;

export function Suggest(arg1:string):Promise<Array<tianyancha.SuggestItem>>;
