// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHolder(arg1) {
  return window['go']['tianyancha']['Bridge']['GetHolder'](arg1);
}

export function GetInvestee(arg1) {
  return window['go']['tianyancha']['Bridge']['GetInvestee'](arg1);
}

export function SearchCompanyV4() {
  return window['go']['tianyancha']['Bridge']['SearchCompanyV4']();
}

export function SetAuth(arg1) {
  return window['go']['tianyancha']['Bridge']['SetAuth'](arg1);
}

export function Suggest(arg1) {
  return window['go']['tianyancha']['Bridge']['Suggest'](arg1);
}
