// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRunningTask() {
  return window['go']['application']['Application']['CheckRunningTask']();
}

export function CheckUpdate() {
  return window['go']['application']['Application']['CheckUpdate']();
}

export function EvenDetail() {
  return window['go']['application']['Application']['EvenDetail']();
}

export function Exit() {
  return window['go']['application']['Application']['Exit']();
}

export function Fetch(arg1) {
  return window['go']['application']['Application']['Fetch'](arg1);
}

export function GetAllConstants() {
  return window['go']['application']['Application']['GetAllConstants']();
}

export function GetContext() {
  return window['go']['application']['Application']['GetContext']();
}

export function GetProxyHistory() {
  return window['go']['application']['Application']['GetProxyHistory']();
}

export function SaveDatabaseFile(arg1) {
  return window['go']['application']['Application']['SaveDatabaseFile'](arg1);
}

export function SaveExportDataDir(arg1) {
  return window['go']['application']['Application']['SaveExportDataDir'](arg1);
}

export function SaveLogDataDir(arg1) {
  return window['go']['application']['Application']['SaveLogDataDir'](arg1);
}

export function SaveProxy(arg1) {
  return window['go']['application']['Application']['SaveProxy'](arg1);
}

export function SaveQueryOnEnter(arg1) {
  return window['go']['application']['Application']['SaveQueryOnEnter'](arg1);
}

export function SaveTimeout(arg1) {
  return window['go']['application']['Application']['SaveTimeout'](arg1);
}

export function SaveWechatDataDir(arg1) {
  return window['go']['application']['Application']['SaveWechatDataDir'](arg1);
}

export function SetContext(arg1) {
  return window['go']['application']['Application']['SetContext'](arg1);
}

export function UseProxyManager(arg1) {
  return window['go']['application']['Application']['UseProxyManager'](arg1);
}

export function WriteConfig(arg1) {
  return window['go']['application']['Application']['WriteConfig'](arg1);
}
