// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {event} from '../models';
import {application} from '../models';
import {context} from '../models';
import {config} from '../models';
import {time} from '../models';
import {proxy} from '../models';

export function CheckRunningTask():Promise<void>;

export function CheckUpdate():Promise<{[key: string]: string}>;

export function EvenDetail():Promise<event.EventDetail>;

export function Exit():Promise<void>;

export function Fetch(arg1:string):Promise<Array<number>>;

export function GetAllConstants():Promise<application.Constant>;

export function GetContext():Promise<context.Context>;

export function GetWechatRules():Promise<Array<string>>;

export function SaveDatabaseFile(arg1:string):Promise<void>;

export function SaveExportDataDir(arg1:string):Promise<void>;

export function SaveICPConfig(arg1:config.ICP):Promise<void>;

export function SaveLogDataDir(arg1:string):Promise<void>;

export function SaveProxy(arg1:config.Proxy):Promise<void>;

export function SaveQueryOnEnter(arg1:config.QueryOnEnter):Promise<void>;

export function SaveTimeout(arg1:time.Duration):Promise<void>;

export function SaveWechat(arg1:config.Wechat):Promise<void>;

export function SaveWechatDataDir(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UseProxyManager(arg1:proxy.Manager):Promise<void>;

export function WriteConfig(arg1:config.Config):Promise<void>;
