// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {properties} from '../models';
import {shodan} from '../models';

export function GetGeneral():Promise<properties.General>;

export function GetHTTP():Promise<properties.HTTP>;

export function GetUserInfo():Promise<shodan.User>;

export function HostSearch(arg1:number,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<shodan.HostSearchResult>;

export function SetAuth(arg1:string):Promise<void>;
