// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGeneral() {
  return window['go']['shodan']['Bridge']['GetGeneral']();
}

export function GetHTTP() {
  return window['go']['shodan']['Bridge']['GetHTTP']();
}

export function GetUserInfo() {
  return window['go']['shodan']['Bridge']['GetUserInfo']();
}

export function HostSearch(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['shodan']['Bridge']['HostSearch'](arg1, arg2, arg3, arg4, arg5);
}

export function SetAuth(arg1) {
  return window['go']['shodan']['Bridge']['SetAuth'](arg1);
}
