// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Export(arg1, arg2, arg3) {
  return window['go']['fofa']['Bridge']['Export'](arg1, arg2, arg3);
}

export function GetUserInfo() {
  return window['go']['fofa']['Bridge']['GetUserInfo']();
}

export function Query(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['fofa']['Bridge']['Query'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetAuth(arg1) {
  return window['go']['fofa']['Bridge']['SetAuth'](arg1);
}
