// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fofa} from '../models';

export function Export(arg1:number,arg2:number,arg3:number):Promise<number>;

export function GetUserInfo():Promise<fofa.User>;

export function HostAggs(arg1:string):Promise<fofa.HostAggsResult>;

export function Query(arg1:number,arg2:string,arg3:number,arg4:number,arg5:string,arg6:boolean):Promise<fofa.QueryResult>;

export function SetAuth(arg1:string):Promise<void>;

export function StatisticalAggs(arg1:string,arg2:string):Promise<fofa.StatisticalAggsResult>;
