// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Export(arg1, arg2, arg3) {
  return window['go']['hunter']['Bridge']['Export'](arg1, arg2, arg3);
}

export function GetRestToken() {
  return window['go']['hunter']['Bridge']['GetRestToken']();
}

export function Query(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['hunter']['Bridge']['Query'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SetAuth(arg1) {
  return window['go']['hunter']['Bridge']['SetAuth'](arg1);
}
