// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hunter} from '../models';

export function Export(arg1:number,arg2:number,arg3:number):Promise<void>;

export function GetRestToken():Promise<number>;

export function Query(arg1:number,arg2:string,arg3:number,arg4:number,arg5:string,arg6:string,arg7:number,arg8:string,arg9:boolean):Promise<hunter.QueryResult>;

export function SetAuth(arg1:string):Promise<void>;
